name: Create Weekly Task Issue
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1

jobs:
  create_issue:
    name: Create Weekly Task Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        run: |
          gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: ログインセッション値が追加されたかどうかを確認する
          ASSIGNEES: jun-takagi-sddgrp
          LABELS: feature
          BODY: |
            ### Task

            - [ ] system_value_parameters と `app/Libraries/Authentication.php` に定義しているログインセッション値取得メソッドの差分を確認する
