name: Create Weekly Task Issue
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1

jobs:
  create_issue:
    name: Create Weekly Task Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        run: |
          gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: ログインセッション値の差分を確認する
          ASSIGNEES: jun-takagi-sddgrp
          BODY: |
            ### Task

            - [ ] `Authentication.php` と `system_value_parameters` の差分を確認する
